[build]
  command = "yarn build"
  publish = "build"
  functions = "functions"

[build.environment]
  YARN_VERSION = "stable" 

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"
